# Generated by Django 5.2.16 on 2026-07-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('poste', models.CharField(choices=[('Gardien', 'Gardien'), ('Défenseur', 'Défenseur'), ('Milieu', 'Milieu'), ('Attaquant', 'Attaquant')], max_length=20)),
                ('date_naissance', models.DateField()),
                ('club_actuel', models.CharField(max_length=150)),
                ('nationalite', models.CharField(max_length=100)),
                ('pied_fort', models.CharField(choices=[('Droit', 'Droit'), ('Gauche', 'Gauche'), ('Ambidextre', 'Ambidextre')], max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='joueurs/')),
                ('video', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('matchs', models.PositiveIntegerField(default=0)),
                ('buts', models.PositiveIntegerField(default=0)),
                ('passes_decisives', models.PositiveIntegerField(default=0)),
                ('mis_en_avant', models.BooleanField(default=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
