server {
    listen 80;
    listen [::]:80;
    server_name spm.harounc.com;

    client_max_body_size 12M;

    location /static/ {
        alias /var/www/spm/staticfiles/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /var/www/spm/media/;
        expires 7d;
        add_header X-Content-Type-Options nosniff always;
    }

    location / {
        include proxy_params;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://unix:/run/spm/gunicorn.sock;
    }
}
