# Generated by Django 5.2.16 on 2026-07-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='actualites/')),
                ('extrait', models.TextField(max_length=350)),
                ('contenu', models.TextField()),
                ('publie', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
